### ISSUE TITLE
DEBUGGING constant

### ISSUE THREAD

**Issue by MadcapJake** [tokuhirom/p6-HTTP-Server-Tiny#26]
Since `DEBUGGING` is set in a constant, it only checks for the environment variable at compile time.  Thus it's impossible to turn this on or off it only checks once for HST_DEBUG when installing the module.

Perhaps just stick it in a regular variable or you could probably make it a constant sub.

**Comment by tokuhirom** [comment]
It's a variable for HTTP::Server::Tiny's author.
It removes in compiling for performance reason.

**Comment by MadcapJake** [comment]
Somehow though it was on for me, I couldn't turn it off without changing the constant to a sub. At some point I did have `HST_DEBUG` set but then unsetting it did nothing to remove the debugging log messages.
