### ISSUE TITLE
Trying to run on already-taken port gives non-descriptive error

### ISSUE THREAD

**Issue by zoffixznet** [tokuhirom/p6-HTTP-Server-Tiny#40]
I ran the synopsis code and got this output:
```
$ perl6 viewer.p6 
http server is ready: http://127.0.0.1:8080/ (pid:11991, keepalive: 1)
Tried to get the result of a broken Promise
  in method run at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/41D120CC8C5AC1ADBAA2CC7E606E4F8710D84044 (HTTP::Server::Tiny) line 494
  in block <unit> at viewer.p6 line 7

Original exception:
    Died with X::AdHoc+{X::Promise::Broken}
      in method run at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/41D120CC8C5AC1ADBAA2CC7E606E4F8710D84044 (HTTP::Server::Tiny) line 494
      in block <unit> at viewer.p6 line 7

```

And the reason was due to port 8080 already being in use by another service.

**Comment by jonathanstowe** [comment]
The crap error message is probably something LTA in the  ```react``` code, the promise in question being the one that controls exit of the "loop",  there should be a better message when there is an abnormal exit in one of the ```whenever``` supplies.   A ```QUIT``` block sorts it for this code however.  Will push a fix in a minute (it's got to be better than IBM MQ ....)
