### ISSUE TITLE
p6w.input must be a Supply according to P6W spec (Bailador incompatibility)

### ISSUE THREAD

**Issue by ufobat** [tokuhirom/p6-HTTP-Server-Tiny#49]
according to the P6W spec that could be found at https://github.com/zostay/P6W `p6w.input` must be a Supply. This leads into an incompatibility with Bailador. Probably that was what has happend in the video 
https://fosdem.org/2017/schedule/event/webdev_perl6/ ( at minute 10 )

**Comment by tokuhirom** [comment]
ok, we'll fix it
