### ISSUE TITLE
Regression: P6W app must return Promise

### ISSUE THREAD

**Issue by zoffixznet** [tokuhirom/p6-HTTP-Server-Tiny#56]
Fired up my old app on updated module and it now spews `P6W app must return Promise` warning (or error?).

Tried the example in SYNOPSIS and it has the same issue:

```
http server is ready: http://0.0.0.0:3334/ (pid:19649, keepalive: 1)
P6W app must return Promise
  in sub  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/41D120CC8C5AC1ADBAA2CC7E606E4F8710D84044 (HTTP::Server::Tiny) line 277
P6W app must return Promise
  in sub  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/41D120CC8C5AC1ADBAA2CC7E606E4F8710D84044 (HTTP::Server::Tiny) line 277
P6W app must return Promise
  in sub  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/41D120CC8C5AC1ADBAA2CC7E606E4F8710D84044 (HTTP::Server::Tiny) line 277
```

**Comment by zoffixznet** [comment]
Looking at the blame, seems the change is from @ufobat in https://github.com/tokuhirom/p6-HTTP-Server-Tiny/commit/8568bb2bcd6643e69a795c58580270da02f22cb3

I don't understand why a "tiny" server is forcing me to schedule a whole promise just for it to immediately return a string I want to output. That's just poor design.

**Comment by astj** [comment]
The message should be warning, and the app should still works. Isn't it? If not it's apparently a bug, and I'll fix it.
(The message is introduced in #51.)

The reason why this module expects apps to return a Promise is, [P6W](https://github.com/zostay/P6W) 0.7 Draft specification.
It recommends apps and servers to use "request-response" protocol, in which apps return a Promise.
I can understand this is beyond "tiny", but I think it's necessary as long as this module works as P6W's application server.

**Comment by zoffixznet** [comment]
I think it's beyond anything—tiny or otherwise. You're blindly implementing a "specification" of questionable design. Forcing users to use up their threads just to instantly return a tiny string in a language whose performance is its biggest drawback is asinine.

**Comment by tokuhirom** [comment]
@zoffixznet

okay, i understood your suggestion.
i'll support psgi compatible mode in this module again.
